In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('Sensor.csv')
#print(data)

x = np.asanyarray(data.drop(columns=['D']))
y = np.asanyarray(data[['D']])
#print('\n',y)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn import metrics

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1)

In [ ]:
def resultados (model,x_test,y_test):
  y_pred = model.predict(x_test)

  print('Metricas: \n', metrics.classification_report(y_test,y_pred))
  print('matriz de confusion: \n', metrics.confusion_matrix(y_test,y_pred))

In [ ]:
from sklearn.svm import SVC

model = Pipeline([('scaler', StandardScaler()),('cla',SVC())])
model.fit(x_train,y_train.ravel())

print('Train score: ', model.score(x_train, y_train))
print('Test score: ', model.score(x_test, y_test))

resultados(model,x_test,y_test)

Train score:  0.9872427983539095
Test score:  0.9777777777777777
Metricas: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       1.00      0.97      0.99        35
           2       1.00      1.00      1.00        26
           3       0.96      1.00      0.98        25
           4       1.00      1.00      1.00        34
           5       1.00      1.00      1.00        30
           6       0.96      1.00      0.98        27
           7       0.92      0.92      0.92        24
           8       0.94      0.92      0.93        37

    accuracy                           0.98       270
   macro avg       0.98      0.98      0.98       270
weighted avg       0.98      0.98      0.98       270

matriz de confusion: 
 [[32  0  0  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  1  0  0]
 [ 0  0 26  0  0  0  0  0  0]
 [ 0  0  0 25  0  0  0  0  0]
 [ 0  0  0  0 34  0  0  0  0]
 [ 0  0  0  0  0 30  0  0  0]
 [ 0  0  0  0  

In [ ]:
from sklearn.neural_network import MLPClassifier

model = Pipeline([('scaler', StandardScaler()),('cla',MLPClassifier())])
model.fit(x_train,y_train.ravel())

print('Train score: ', model.score(x_train, y_train))
print('Test score: ', model.score(x_test, y_test))

resultados(model,x_test,y_test)

Train score:  0.9880658436213992
Test score:  0.9814814814814815
Metricas: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       1.00      0.97      0.99        35
           2       1.00      1.00      1.00        26
           3       0.96      1.00      0.98        25
           4       1.00      1.00      1.00        34
           5       1.00      1.00      1.00        30
           6       0.96      1.00      0.98        27
           7       0.92      0.96      0.94        24
           8       0.97      0.92      0.94        37

    accuracy                           0.98       270
   macro avg       0.98      0.98      0.98       270
weighted avg       0.98      0.98      0.98       270

matriz de confusion: 
 [[32  0  0  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  1  0  0]
 [ 0  0 26  0  0  0  0  0  0]
 [ 0  0  0 25  0  0  0  0  0]
 [ 0  0  0  0 34  0  0  0  0]
 [ 0  0  0  0  0 30  0  0  0]
 [ 0  0  0  0  

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
